### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by laiba49**
Please See

### CODE REVIEW

**Comment by ridaayaz** [comment]
A.o.A ..laiba also upload the CSS file in repo cuz you only upload the HTML one.

**Comment by laiba49** [comment]
Okkk...ma thori fair thk Kar data hon..

**Comment by ridaayaz** [comment]
great :)

**Comment by ridaayaz** [comment]
Good Job :D .. Let's Merge it

**Comment by laiba49** [comment]
But you said that you are allowed to merge because you check my work....?

**Comment by ridaayaz** [comment]
Yes. that's why i have merged it :). Relaxx

**Comment by laiba49** [comment]
Ok

**Pull request merged**
